# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 825758aa2501f247b23cb4d947650b5692140005df5ed192a58b5a4e1135f9d70736447c7e2ad9d372931f3de9ad68c12c818d590dea8ed20db422f3124ee442

test:
  secret_key_base: 17824ff23cff7dbb6ed9445373ba5f1dda4eb06f2c08a05bcfc7624605096a81f0c26558d94d6ba5fcedccd27e1271fe4f93c4907246fbbd2a03494b5c263d46

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
